### ISSUE TITLE
Setup Authentication

### ISSUE THREAD

**Issue by zupey** [usdevs/uscwebsite-hackathon-backend#14]
The plan is to use telegram to authenticate user.  

The login workflow is as follows:

1. Telegram authentication using telegram login widget (github pages in dev)
2. Send authentication details to backend /login route
3. Check authenticity of data
4. Check if tele_id exists and populate table if handle exists
5. Generate session token

**Comment by misterpuffin** [comment]
Good point on CSRF attacks, thanks for sharing. I think the more convenient way without CSRF tokens would likely to restrict all http requests to our API to have `Content-Type: application/json`.

I think online time-based attack might be less relevant for our application. This is because all operations will require a database query, regardless on whether the telegram_id exists or doesn't exist in our application. I suppose if `telegram_id` doesn't exist, we might need to perform an additional db query to check for `telegram_username`, but we can circumvent this by combining the 2 conditions in our first query. (I might be wrong)

**Comment by zupey** [comment]
Ok, restricting http requests to `Content-Type: application/json` is a good idea.

Ya, time-based attack is prob not as relevant now that I think about it.

Thanks for your input
